name: DepthAI Demo CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:

  windows-installer:
    runs-on: windows-latest

    steps:

    # Clones repository without persisting credentials
    # As this local git repository is packed with installer
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        persist-credentials: ''

    - name: Build Windows Installer
      run: .\launcher\windows\build.ps1

    - name: Upload Installer artifact
      uses: actions/upload-artifact@v2
      with:
        name: installers
        path: launcher/windows/build/Output/
        retention-days: 5


  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:

    - name: Download Windows installer
      uses: actions/download-artifact@v2
      with:
        name: 'installers'
        path: installers

   # Sign Launcher
    - name: Sign Windows Launcher
      run: |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ secrets.WINDOWS_CERTIFICATE }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /td sha256 /fd sha256 /f certificate\certificate.pfx /p '${{ secrets.WINDOWS_CERTIFICATE_PASS }}' /tr http://timestamp.digicert.com installers/DepthAI_setup.exe
   # Fetches previous tag
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
   # Create GitHub release
    - uses: actions/create-release@master
      id: createRelease
      name: Create ${{ steps.tag.outputs.version }} DepthAI Demo release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: DepthAI Demo ${{ github.ref }}
        body: |
          ## Features

          ## Bugs

          ## Misc

          **Full Changelog**: https://github.com/luxonis/depthai/compare/${{ steps.previoustag.outputs.tag }}...${{ github.ref }}

        draft: true

    # Upload release assets
    - name: Upload Windows Installer
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.createRelease.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/installers/DepthAI_setup.exe
        asset_name: DepthAI-setup-${{ steps.tag.outputs.version }}.exe
        asset_content_type: application/octet-stream
