 name: Test requirements installation

 on:
  workflow_dispatch:
  push:
    paths:
      - 'install_requirements.py'
      - '.github/workflows/test_install_requirements.yml'

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   install_dependencies_linux:
     runs-on: ubuntu-latest
     strategy:
       matrix:
          container_image: ["fedora:34", "fedora:35", "fedora:36", "ubuntu:20.04", "ubuntu:22.04"]
     container:
       image: ${{ matrix.container_image }}
     steps:
       - uses: actions/checkout@v3
       - name: Install sudo
         if: startsWith(matrix.container_image, 'fedora') == true
         run: yum update -y && yum install -y sudo curl
       - name: Install sudo
         if: startsWith(matrix.container_image, 'ubuntu') == true
         run: apt-get update  -qq && apt-get -qq install sudo curl
       - name: Install dependencies
         run: |
           ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
           curl -fL https://docs.luxonis.com/install_dependencies.sh > install_dependencies.sh
           sed '/udevadm control --reload-rules && sudo udevadm trigger/d' install_dependencies.sh > tmp_script.sh
           bash tmp_script.sh
       - name: Install example requirements
         run: |
           python3 install_requirements.py
   install_dependencies_macos:
      runs-on: macos-latest
      steps:
       - uses: actions/checkout@v3
       - name: Install dependencies
         run: |
           curl -fL https://docs.luxonis.com/install_dependencies.sh > install_dependencies.sh
           sed '/udevadm control --reload-rules && sudo udevadm trigger/d' install_dependencies.sh > tmp_script.sh
           bash tmp_script.sh
       - name: Install example requirements
         run: |
           sudo rm -rf /Library/Developer/CommandLineTools
           sudo xcode-select --install
           python3 install_requirements.py
